/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_menu (void);
GtkWidget* create_about (void);

int setvol(int vol);
void setmute();
int getvol();
void get_current_levels();
int get_mute_state();
void hide_me();
